### PR TITLE
Reworked Contact points, renamed plane, added new thumbnail, repositioned cockpit camera

### PR DESCRIPTION
**Pull request by tjburni**
Reworked Contact points, renamed plane, added new thumbnail, repositioned cockpit camera

### CODE REVIEW

**Comment by Percival289** [comment]
Please provide screenshots of the changes (upload new thumbnail/screenshot the aircraft with the correct contact points)

**Comment by Percival289** [comment]
In the future, please create an issue before you start so that other people know you’re working on it (to prevent duplicate PRs).

**Comment by tjburni** [comment]
Here are the images of the new Thumbnail and contact points
thumbnail
Screenshot 2021-05-12 224528
Screenshot 2021-05-12 224545

**Review by Percival289 — APPROVED** [review]

**Comment by HugoTro** [comment]
Just a little question on your PR (even if it's already merged now), why are there contact points on the middle of the engine (red) and none at the correct location of the underside of the engine? (blue)image

**Comment by tjburni** [comment]
> Just a little question on your PR (even if it's already merged now), why are there contact points on the middle of the engine (red) and none at the correct location of the underside of the engine? (blue)image

oh yeah you're right lol i'll change that with the next PR

**Pull request merged**
